version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_challenge
    ports:
      - 27017:27017
  app:
    image: magnaldomelo/challenge-back-vote
    ports:
      - 8080:8080
    links:
      - mongodb
      - kafka
  redis:
    container_name: redis_challenge
    image: redis:5.0.7-buster
    ports:
      - "6379:6379"
    volumes:
      - /var/magnaldomelo/master/redis/data:/data:rw
    entrypoint: redis-server --appendonly yes
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
