server:
  servlet:
    context-path: '/api/v1'
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 'challenge-back-vote'
  data:
    mongodb:
      host: mongo_db
      port: 27017
      database: challenge_back_vote
  redis:
    host: redis
    port: 6379
    ttl:
      default: 30m
    timeout: 10000
    database: 1
    jedis:
      pool:
        max-active: 32
        max-idle: 2
        min-idle: 1
  kafka:
    producer:
      bootstrap-servers: kafka:9093
      group-id: section-result-consumer-group
    consumer:
      bootstrap-servers: kafka:9092
      group-id: section-result-consumer-group

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

application:
  usersservice:
    url: https://user-info.herokuapp.com

pool:
  usersservice:
    maxConn: 100
    maxRoutes: 200
    connTimeout: 60000
    readTimeout: 60000

feign:
  httpclient:
    max-connections: 100
    connection-timeout: 2000

generalconfig:
  default-minutes-to-finish: 1
  result-kafka-topic: messaging-result-topic-2
